### ISSUE TITLE
.main-content block does not have fixed width and pushes .sidebar out of .wrapper

### ISSUE THREAD

**Issue by alexoleynik0** [DrAradia/resume-project1#2]
Steps to reproduce: 

1. Go to your `h1.my-name` and put there some long text without whitespaces, eg "MariiaDavydenkoMariiaDavydenkoMariiaDavydenko". 
0. See the layout break -- the `.main-content` block gets wider, the`.sidebar` goes beyond the `.wrapper` (which can be seen better if you add `overflow: hidden;` to `.wrapper` element). 

Expected behavior: 
1. The `.main-content` stays 830px in width. 
0. Long words without whitespaces wrap to the next line. 
0. `.sidebar` stays where it was.

**Comment by alexoleynik0** [comment]
Hey, ping ping! Are you planning on fixing this issue at all? Or are you choosing the life of an adventurer?

**Comment by DrAradia** [comment]
Yeah but a bit later (

нд, 12 лист. 2023, 15:01 користувач Alex Oleynik ***@***.***>
пише:

**Comment by alexoleynik0** [comment]
Ok ok.. please stop sending me all that respond history, it's annoying, I
don't want to live in the past 😔

upd: oh sht I did that, too ))

**Comment by alexoleynik0** [comment]
Ok ok, I get it.. Have a nice time doing something **really** fun 🥲

**Comment by alexoleynik0** [comment]
All the hope is gone..
